language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

# when https://github.com/travis-ci/apt-package-whitelist/issues/792 is closed, use the container-based infrastructure
#sudo: false
#addons:
#  apt:
#    packages:
#    - mlton

# brew install mlton doesn't seem to work (https://github.com/travis-ci/travis-ci/issues/5379)
matrix:
  allow_failures:
    - os: osx

before_install:
  - if command -v apt-get &>/dev/null; then sudo apt-get update -qq; fi
  - if command -v apt-get &>/dev/null; then sudo apt-get install -y mlton; fi
  - if command -v brew &>/dev/null; then brew update; fi
  - if command -v brew &>/dev/null; then brew install mlton; fi

script: ./autogen.sh && ./configure && make && make test
